In [45]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [46]:
df=pd.read_csv("intrusion_detection/data_lower.csv")
k = 5

In [47]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [48]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([1, 1, 3, ..., 1, 3, 1], dtype=int32)

In [49]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8652250879156644

In [50]:
ypred = kmeans.predict(X)
print(ypred)

[1 1 3 ... 1 3 1]


In [51]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [52]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [53]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

25.74309946652235


In [54]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

30.52893792662098
FLAG= False
1
13.35534881185655
FLAG= False
2
2.6765978175938434
FLAG= False
3
1.0080744725912696
FLAG= False
4
0.30563037459128284
FLAG= False
5
0.042526035014949434
FLAG= False
6
0.01898671028475082
FLAG= False
7
0.005336365963367095
FLAG= False
8
0.0016145217982989073
FLAG= False
9
0.000537845078907426
FLAG= False
10
0.0005140864550458033
FLAG= False
11
0.0
FLAG= False
12


In [55]:
clusters

array([1, 1, 0, ..., 1, 0, 1])

In [56]:
# centers_new

In [57]:
cont = contingency_matrix(clusters,Y)
cont

array([[  130, 34332,     1,   401,     0],
       [63120,  2464,   509,  1873,    44],
       [ 2794,  6896,     0,  5307,     0],
       [  155,     0,    54,     2,     1],
       [ 1144,  2235,   431,  4073,     7]])

In [58]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8618989783525041