In [51]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [52]:
df=pd.read_csv("intrusion_detection/data_lower.csv")
k = 5

In [53]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [54]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 0, 1, ..., 0, 1, 0], dtype=int32)

In [55]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8384415708127932

In [56]:
ypred = kmeans.predict(X)
print(ypred)

[0 0 1 ... 0 1 0]


In [57]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [58]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [59]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

22.78661506883631


In [60]:
iteration = 0
force = False
while (error != 0 or force==True) and iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

38.616081707230606
FLAG= False
1
12.996801311186074
FLAG= False
2
17.221525543053275
FLAG= False
3
13.119892405618652
FLAG= False
4
12.06805360377629
FLAG= False
5
3.7779201731473004
FLAG= False
6
1.100762053542842
FLAG= False
7
0.01221839975015023
FLAG= False
8
0.0072748445908544105
FLAG= False
9
0.004947758840605863
FLAG= False
10
0.003780894082039546
FLAG= False
11
0.0021159506268987375
FLAG= False
12
0.0017794747597693727
FLAG= False
13
0.000323144187055571
FLAG= False
14
0.0003927967496499736
FLAG= False
15
0.00036453699871070305
FLAG= False
16
0.0
FLAG= False
17


In [61]:
clusters

array([3, 1, 4, ..., 1, 4, 3])

In [62]:
# centers_new

In [63]:
cont = contingency_matrix(clusters,Y)

In [64]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8386241496193628