In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
df=pd.read_csv("intrusion_detection/data_lower.csv")
k = 5

In [3]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [4]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([1, 0, 2, ..., 1, 2, 1], dtype=int32)

In [5]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8385368293205687

In [6]:
ypred = kmeans.predict(X)
print(ypred)

[1 0 2 ... 1 2 1]


In [7]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [8]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [9]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

21.54890973876367


In [10]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

41.676094422004724
FLAG= False
1
4.181483019890768
FLAG= False
2
3.9981246625990923
FLAG= False
3
3.59530218623082
FLAG= False
4
0.8087438230772831
FLAG= False
5
0.20465388176634652
FLAG= False
6
0.05663932136744028
FLAG= False
7
0.031775096450900236
FLAG= False
8
0.024650880637072863
FLAG= False
9
0.010411791504422375
FLAG= False
10
0.0041308046312268755
FLAG= False
11
0.003238402324147176
FLAG= False
12
0.0031778559527150226
FLAG= False
13
0.0024593777429282337
FLAG= False
14
0.002377928914160173
FLAG= False
15
0.0017993566507603148
FLAG= False
16
0.0011381841329630427
FLAG= False
17
0.0010907285206494728
FLAG= False
18
0.0016968427254873796
FLAG= False
19
0.0026421543057233957
FLAG= False
20
0.004314418660474201
FLAG= False
21
0.004696665139154961
FLAG= False
22
0.004565460654527947
FLAG= False
23
0.004903545214929799
FLAG= False
24
0.004097826450797169
FLAG= False
25
0.0029160367442045846
FLAG= False
26
0.0037350020923156836
FLAG= False
27
0.006016625987349455
FLAG= False
28
0.0057

In [11]:
clusters

array([3, 3, 4, ..., 3, 4, 3])

In [12]:
# centers_new

In [13]:
cont = contingency_matrix(clusters,Y)
cont

array([[ 1341,   126,   710,  4077,     9],
       [ 2783,  6896,     0,  5306,     0],
       [   68,     0,    52,     4,     1],
       [63017,  4565,   232,  1868,    42],
       [  134, 34340,     1,   401,     0]])

In [14]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8604859771538346