In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
df=pd.read_csv("intrusion_detection/data_lower.csv")
k = 5

In [3]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [4]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([3, 3, 0, ..., 3, 0, 3], dtype=int32)

In [5]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8652330261246458

In [6]:
ypred = kmeans.predict(X)
print(ypred)

[3 3 0 ... 3 0 3]


In [7]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [8]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [9]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

29.04263722123636


In [10]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

24.348813741446733
FLAG= False
1
17.240894055349347
FLAG= False
2
16.919986088816657
FLAG= False
3
14.224928850444796
FLAG= False
4
4.296674175340087
FLAG= False
5
4.03382259624262
FLAG= False
6
9.871566249599951
FLAG= False
7
7.922987312793602
FLAG= False
8
2.8392604243104707
FLAG= False
9
0.0
FLAG= False
10


In [11]:
clusters

array([4, 4, 3, ..., 4, 3, 4])

In [12]:
# centers_new

In [13]:
cont = contingency_matrix(clusters,Y)
cont

array([[ 2812,  6896,    49,  5309,     0],
       [ 6635,  2352,     0,    51,     0],
       [   32,     0,     0,     0,     0],
       [  130, 34334,     2,   401,     0],
       [57734,  2345,   944,  5895,    52]])

In [14]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8385209529026061