In [132]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import numpy as np
import pandas as pd
import random
import math
import copy

In [133]:
df=pd.read_csv("intrusion_detection/data_lower.csv")
k = 5

In [134]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [135]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 0, 1, ..., 0, 1, 0], dtype=int32)

In [136]:
kmeans.cluster_centers_
cn = confusion_matrix(clusters,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8652727171695522

In [137]:
ypred = kmeans.predict(X)
print(ypred)

[0 0 1 ... 0 1 0]


In [138]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [139]:
centers_old = np.zeros([k,14])
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean

error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

# error = np.linalg.norm(centers_new - centers_old)
print(error)
iteration = 0
force = False
while (error != 0 or force==True) and iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

for i in range(k):
    distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
clusters = np.argmin(distances, axis = 1)
clusters

24.549051978584075
23.920178820820702
FLAG= False
1
8.19874730081547
FLAG= False
2
1.9682206803324311
FLAG= False
3
1.0555017202373018
FLAG= False
4
0.5305565679828447
FLAG= False
5
0.32289863513864586
FLAG= False
6
0.4500937079302102
FLAG= False
7
0.5471922526722656
FLAG= False
8
0.27671498062960337
FLAG= False
9
0.1264427936147359
FLAG= False
10
0.06170234006647407
FLAG= False
11
0.04674518400215298
FLAG= False
12
0.059337518950658266
FLAG= False
13
0.07484776685735722
FLAG= False
14
0.028537503018354962
FLAG= False
15
0.021111150134492673
FLAG= False
16
0.0006500815524272258
FLAG= False
17
0.0
FLAG= False
18


array([4, 4, 1, ..., 4, 1, 4])

In [140]:
centers_new

array([[ 3.26766645e+00, -5.05017434e-01,  3.57399663e-01,
         3.80432388e+00, -2.22203912e+00, -1.62837012e+00,
        -2.83846189e-02, -4.89508533e-01,  5.51059165e-02,
        -2.51701704e-02,  4.07578156e-02, -4.38856428e-01,
         5.92551058e-02, -1.21567566e-02],
       [-3.75890305e+00, -1.22103815e+00,  1.46354513e-02,
         2.71363857e-01, -7.73413826e-04, -2.54088449e-01,
         1.64298165e-01,  1.73610635e-02,  2.45227526e-02,
         4.93281291e-03,  9.18654451e-03,  6.10950097e-02,
        -5.16560438e-03,  7.06223034e-02],
       [ 1.18072433e+00, -3.79754810e-01,  1.18210437e-01,
        -1.50479410e-01,  1.69910958e+00,  3.14620938e+00,
        -7.05116475e-02, -9.33083176e+00,  6.56862538e+00,
         1.02776952e+00, -3.05868734e-01, -3.09877331e-01,
         8.63294933e-01, -1.31700919e+00],
       [-4.83352279e-01,  5.68649872e+00, -1.01411360e-01,
        -2.23775371e-01,  2.58596231e-01, -6.23948294e-01,
         2.46842874e-01, -4.00718831e-02,  1.

In [141]:
cn = confusion_matrix(clusters,Y)

In [142]:
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8652171497066832